/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zhzl_myapp_JNIHelper */

#ifndef _Included_com_example_zhzl_myapp_JNIHelper
#define _Included_com_example_zhzl_myapp_JNIHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zhzl_myapp_JNIHelper
 * Method:    nativeSetApkPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_zhzl_myapp_JNIHelper_nativeSetApkPath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
