/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zhzl_myapp_GLES3JNILib */

#ifndef _Included_com_example_zhzl_myapp_GLES3JNILib
#define _Included_com_example_zhzl_myapp_GLES3JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zhzl_myapp_GLES3JNILib
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zhzl_myapp_GLES3JNILib_init
  (JNIEnv *, jclass);

/*
 * Class:     com_example_zhzl_myapp_GLES3JNILib
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_zhzl_myapp_GLES3JNILib_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_zhzl_myapp_GLES3JNILib
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zhzl_myapp_GLES3JNILib_step
  (JNIEnv *, jclass);

/*
 * Class:     com_example_zhzl_myapp_GLES3JNILib
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zhzl_myapp_GLES3JNILib_nativeOnPause
  (JNIEnv *, jclass);

/*
 * Class:     com_example_zhzl_myapp_GLES3JNILib
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zhzl_myapp_GLES3JNILib_nativeOnResume
  (JNIEnv *, jclass);

/*
 * Class:     com_example_zhzl_myapp_GLES3JNILib
 * Method:    nativeTouchesBegin
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_example_zhzl_myapp_GLES3JNILib_nativeTouchesBegin
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_example_zhzl_myapp_GLES3JNILib
 * Method:    nativeTouchesEnd
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_example_zhzl_myapp_GLES3JNILib_nativeTouchesEnd
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_example_zhzl_myapp_GLES3JNILib
 * Method:    nativeTouchesMove
 * Signature: ([I[F[F)V
 */
JNIEXPORT void JNICALL Java_com_example_zhzl_myapp_GLES3JNILib_nativeTouchesMove
  (JNIEnv *, jclass, jintArray, jfloatArray, jfloatArray);

/*
 * Class:     com_example_zhzl_myapp_GLES3JNILib
 * Method:    nativeTouchesCancel
 * Signature: ([I[F[F)V
 */
JNIEXPORT void JNICALL Java_com_example_zhzl_myapp_GLES3JNILib_nativeTouchesCancel
  (JNIEnv *, jclass, jintArray, jfloatArray, jfloatArray);

/*
 * Class:     com_example_zhzl_myapp_GLES3JNILib
 * Method:    nativeKeyEvent
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_zhzl_myapp_GLES3JNILib_nativeKeyEvent
  (JNIEnv *, jclass, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
